### ISSUE TITLE
업무 완료에 의한 신뢰점수 증감과 업무 상태에 대한 문의 @sunggun1

### ISSUE THREAD

**Issue by jkang1201** [oneMonthProject/Backend#147]
오늘 안 계시고 제가 까먹을까 봐 남깁니다.
1. 신뢰점수 +, 신뢰점수 - 했을 때 모든 업무는 "완료상태"인지 문의 드립니다.
2. 신뢰점수 차감했을 때 Work의 완료상태 (complete_status)를 다시 미완료 상태로 바꿔줘야 되는지 문의드립니다.

**Comment by sunggun1** [comment]
@jkang1201  1. 제가 알기로는 완료상태가 아니더라도 +,-가 되는 것 같습니다. 신뢰점수 +, 신뢰점수 -가 업무가 완료상태가 아니더라도 그렇게 되지 않나요?? 병수님 기획에 따라서 조건에 따라 다르지 않나요?

2. 안 바꿔도 되는 것 같습니다. 신뢰점수 차감했을 때가 아니라 업무가 완료가 된 경우에 완료상태가 되어야 하고 신뢰점수 차감과 완료 상태 변경은 아예 다른 거 아닌가요?

**Comment by EUNSUN23** [comment]
@jkang1201 

1. 업무 완료시 신뢰점수를 + 혹은 - 할 수 있구요, 업무 완료가 아닌 상태에서 기한이 마감되면 신뢰점수는 - 만 할 수 있습니다. 
2. 미완료 상태로 바꾸지 않습니다.
