### ISSUE TITLE
data.sql, schema.sql에 테스트 관련 데이터 올려주세요

### ISSUE THREAD

**Issue by sunggun1** [oneMonthProject/Backend#154]
data.sql, schema.sql에 테스트 관련 데이터 올려주세요

@Valid 처리에 대해서 exceptionHandler로 잡아주고 있기는 한데 결과가 좀 별로라서 그런데 Validator랑 exceptionHandler를 같이 적용시켜보는건 어떨까요?

**Comment by jkang1201** [comment]
간단한 개별 필드는 그냥 @Valid로 퉁치고
복잡한 로직이 들어가는 검증에 대해서는 Validator가 나쁘지 않은 것 같습니다
근데 Validator에서 CustomException을 던지는 게 깔끔하긴 한데, 그러면 CustomException이 더더욱 많이 많들어야 되고
그냥 return false 해버리면 그 DTO에 대해서만 문제를 반환하지 DTO 안의 필드에 대해서는 로그를 남기는 것밖에 할 수 있는 게 없을 것 같습니다
정확히 어떤 부분에서 "결과가 좀 별로"인 걸까요?

**Comment by sunggun1** [comment]
package com.example.demo.global;

import com.example.demo.dto.common.ResponseDto;
import com.example.demo.global.customException.CustomException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.util.List;
import java.util.stream.Collectors;

@RestControllerAdvice
public class GlobalExceptionHandler {

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ResponseDto<?>> processValidationError(MethodArgumentNotValidException e) {
        BindingResult bindingResult = e.getBindingResult();

        StringBuilder builder = new StringBuilder();
        for (FieldError fieldError : bindingResult.getFieldErrors()) {
            builder.append("[");
            builder.append(fieldError.getField());
            builder.append("](은)는 ");
            builder.append(fieldError.getDefaultMessage());
            builder.append(" 입력된 값: [");
            builder.append(fieldError.getRejectedValue());
            builder.append("]");
            builder.append("\n");
        }

        final ResponseDto<String> response = ResponseDto.fail("", builder.toString());
        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(response);
    }

    // CustomException
    @ExceptionHandler(CustomException.class)
    public ResponseEntity<ResponseDto<?>> customExceptionHandle(CustomException e) {
        final ResponseDto response = ResponseDto.fail(e.getErrorCode().getMessage());
        return ResponseEntity.status(e.getErrorCode().getStatus()).body(response);
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ResponseDto<?>> ExceptionHandle(Exception e) {
        final ResponseDto response = ResponseDto.fail(e.getMessage());
        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(response);
    }
}

**Comment by sunggun1** [comment]
@jkang1201  위처럼 만들면 한줄에 다 나오게 되더라고요. 이렇게 나오도록 하고 싶어요
