### ISSUE TITLE
프로젝트 상세 조회 api 수정 요청

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#161]
@sunggun1 

**API** : /api/project/{projectId}

**요청 내용**:

프론트 화면에서 프로젝트 상세 페이지를 보시면, 

'업무', '크루', '알림' 탭이 나눠져 있습니다. 

그래서 /api/project/{projectId} 이 API 응답 데이터에는 프로젝트 projectId, name, subject, trustGrade 이정도면 될것 같구요, 

프로젝트 내의 업무 / 크루 / 알림 조회하는 API는 각각 독립되면 좋을것같습니다.

처음 페이지 진입시 프로젝트 관련 모든 데이터를 api하나로 한꺼번에 읽어오면 페이지 로딩시간이 길어질듯 해서요.

**Comment by sunggun1** [comment]
@EUNSUN23 네 알겠습니다

**Comment by sunggun1** [comment]
프로젝트 내의 업무 : /api/work/project/{projectId}
프로젝트 내의 크루 : /api/projectmember/project/{projectId}
프로젝트 내의 알림 조회 : /api/alert/project/{projectId} 
입니다!
