### ISSUE TITLE
프로젝트 상세 > 마일스톤 > 업무조회 api 수정 요청

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#281]
api : /api/work/project/{projectId}/milestone/{mileStoneId}, /api/work/{workId}

요청 내용 : 
위 api 응답값 중 assignedUserId, lastModifiedMember, lastChangeMember는 프론트엔드 화면에서 사용자가 확인할수있는 값이어야 합니다.
사용자 닉네임으로 수정 부탁드립니다.

**Comment by songhyeonpk** [comment]
lastChangeMember는 lastModifiedMember와 동일한 데이턴데 노션에 잘못 적어주신 것 같아요.
assignedUserId -> assignedUserNickname (String 타입)
lastModifiedMember -> lastModifiedMemberNickname (String 타입)
요청사항 반영해서 수정완료했습니다.
