### ISSUE TITLE
크루 상세 페이지 >  크루의 해당 프로젝트 업무이력 api 추가

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#288]
프로젝트 상세 > 크루 상세 페이지 진입시 크루의 해당 프로젝트 업무 이력을 조회하는 api가 필요합니다. 

![CE3CD11F-5C22-47E2-958E-57D02C7BFA14](https://github.com/oneMonthProject/Backend/assets/60612115/6fc608e1-50b6-4e68-b933-865532d69908)

api 조회 데이터 다음 같이 주실 수 있을까요? 

content : 업무 content
startDate : 업무 시작 날짜 
endDate : 업무 종료 날짜 
progressStatus : 업무 진행 상황 ('시작전', '진행중', '완료', '만료')
point : 업무로 인해 부여받은 신뢰점수 
point_type : 신뢰점수 타입 (plus 혹은 minus)

**Comment by EUNSUN23** [comment]
이슈 확인 부탁드립니다~

**Comment by EUNSUN23** [comment]
이슈 확인 부탁드립니다

**Comment by songhyeonpk** [comment]
해당 API 페이징 필요한가요?

**Comment by songhyeonpk** [comment]
저번과 동일하게 드리면 될까요?

**Comment by EUNSUN23** [comment]
> 저번과 동일하게 드리면 될까요?
네넵

**Comment by songhyeonpk** [comment]
정렬도 필요할까요?

**Comment by EUNSUN23** [comment]
> 정렬도 필요할까요?

넵 업무 시작날짜 기준 최신 -> 이전 날짜 순으로 주시면 될 것 같아요

**Comment by EUNSUN23** [comment]
> ```
> "data": {
>         "content": [
>             {
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용8",
>                 "startDate": "2024-02-01",
>                 "endDate": "2024-02-10",
>                 "progressStatus": "진행중",
>                 "point": null,
>                 "point_type": null
>             },
>             {
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용7",
>                 "startDate": "2024-01-18",
>                 "endDate": "2024-01-20",
>                 "progressStatus": "완료",
>                 "point": 20,
>                 "point_type": "minus"
>             },
>             {
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용6",
>                 "startDate": "2024-01-13",
>                 "endDate": "2024-01-17",
>                 "progressStatus": "완료",
>                 "point": 50,
>                 "point_type": "plus"
>             },
>             {
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용5",
>                 "startDate": "2024-01-11",
>                 "endDate": "2024-01-12",
>                 "progressStatus": "완료",
>                 "point": 50,
>                 "point_type": "minus"
>             },
>             {
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용4",
>                 "startDate": "2024-01-08",
>                 "endDate": "2024-01-10",
>                 "progressStatus": "완료",
>                 "point": 20,
>                 "point_type": "minus"
>             }
>         ],
>         "totalPages": 8
>     }
> ```
> 
> 응답 형태 한번 확인부탁드립니다. 현재 로직이 해당 프로젝트 멤버 정보와 멤버가 속한 프로젝트 정보로 일치하는 업무 목록을 조회하도록 하고 있는데 맞는 로직인가요?

넵 맞습니다
