### ISSUE TITLE
게시글 포지션 지원 api 추가

### ISSUE THREAD

**Issue by moa1128** [oneMonthProject/Backend#291]
![Image](https://github.com/oneMonthProject/Backend/assets/47878904/847b7c44-17cf-4103-b413-23825e390dd9)

게시글 작성자와 다른 사용자가 게시글 상세 페이지 갔을 때 해당 포지션으로 지원하는 기능에 대한 api 가 없는 것 같습니다.
포지션 리스트는 게시글 조회 시 가져와서 따로 필요 없습니다.

**Comment by EUNSUN23** [comment]
위 api 요청 보내면 백엔드 서버에서 프로젝트 이력에 참여 이력으로 저장하면 될 것 같습니다.

**Comment by songhyeonpk** [comment]
```
FORCED_WITHDRAWAL("강제 탈퇴"),
WITHDRAWAL("탈퇴"),
PARTICIPATING("참여중"),
FINISH("완주");
```
현재 프로젝트 이력 상태를 이렇게 설정하고 있는데요.
해당 api를 통해 참여신청을 하면 게시자에게 알림을 보내고 게시자가 수락을 한 경우에 프로젝트 이력에 저장해야 되지 않을까요?
아니면 프로젝트 이력 상태에 "참여신청" enum을 추가해야할까요?

**Comment by moa1128** [comment]
> 해당 api를 통해 참여신청을 하면 게시자에게 알림을 보내고 게시자가 수락을 한 경우에 프로젝트 이력에 저장

포지션 지원 클릭 -> 알림 보내기 -> 수락 -> 프로젝트 참여
@EUNSUN23 저도 이게 맞다고 생각하는데 어떻게 생각하세요?

**Comment by EUNSUN23** [comment]
> ```
> FORCED_WITHDRAWAL("강제 탈퇴"),
> WITHDRAWAL("탈퇴"),
> PARTICIPATING("참여중"),
> FINISH("완주");
> ```
> 
> 현재 프로젝트 이력 상태를 이렇게 설정하고 있는데요. 해당 api를 통해 참여신청을 하면 게시자에게 알림을 보내고 게시자가 수락을 한 경우에 프로젝트 이력에 저장해야 되지 않을까요? 아니면 프로젝트 이력 상태에 "참여신청" enum을 추가해야할까요?

코멘트가 달린줄 몰랐네요.. 네 이게 맞는것같아요. 감사합니다.

**Comment by songhyeonpk** [comment]
/{projectId}/participate: 프로젝트 참여 신청
/api/project/1/participate/confirm: 프로젝트 참여 수락
이렇게 존재하는데 다른 api 인가요?

**Comment by moa1128** [comment]
음 그것보다 코드를 봤을 때
```
/api/alert: 프로젝트 지원 알림 - 외부에서 프로젝트 모집에 지원했을경우 알림, 프로젝트 업무 알림 - 업무나 마일스톤 관련된 알림, ...
/api/project/1/participate: 특정 프로젝트 멤버 참여 기능 (참여 알림 발송)
```

이 두 api 모두 포지션 지원했을 때 알림 생성할 수 있는 것 같습니다.
포지션 지원용으로 만들어진 `/api/project/1/participate` 을 연결하도록 하겠습니다.

> /{projectId}/participate: 프로젝트 참여 신청
/api/project/1/participate/confirm: 프로젝트 참여 수락
이렇게 존재하는데 다른 api 인가요?

![Image](https://github.com/oneMonthProject/Backend/assets/47878904/c7002414-6d4f-426b-895c-908e25407e46)

첫번째 꺼는 포지션 지원하면 알림 생성하는 api 이고, 두번째는 위의 팝업에서 수락 눌렀을 때 프로젝트 멤버가 되는 api 아닌가요?

**Comment by EUNSUN23** [comment]
지은님이 설명하신게 맞아요.

**Comment by moa1128** [comment]
이미 구현된 api 가 있으므로 해당 이슈를 close 하겠습니다.
