### ISSUE TITLE
게시글 생성 시 신뢰등급 리스트 api

### ISSUE THREAD

**Issue by moa1128** [oneMonthProject/Backend#292]
게시글 생성 할 때 신뢰등급 전체 리스트 가져오는 것을 병수님이 구현해주셨는데, 생각해보니 사용자 별 가능한 신뢰등급만 나와야 할 것 같습니다.
아래와 같이 수정 부탁 드립니다.

ex) 현 사용자의 신뢰등급 3등급일 경우, 리스트에는 3등급과 4등급만 담김

**Comment by jkang1201** [comment]
@EUNSUN23 API로 보내드리면 되나요? 그럼 현재 로그인한 사용자 ID 요청값에 보내주실 수 있나요

**Comment by moa1128** [comment]
@jkang1201 
이건 제 이슈 인데요 기존에 게시물 생성 할 때도 그렇고 
따로 user id 없어도 `@AuthenticationPrincipal PrincipalDetails user` 이걸로 가져올 수 있지 않나요?

**Comment by jkang1201** [comment]
기왕이면 안 쓰는 게 좋을 거 같아서요 그리고 "제 이슈" 라는 말씀이 이해가 잘 안 가는데 무슨 뜻이죠

**Comment by EUNSUN23** [comment]
> @EUNSUN23 API로 보내드리면 되나요? 그럼 현재 로그인한 사용자 ID 요청값에 보내주실 수 있나요

요청값에 보내줄수 있을거에요. 이건 지은님께 말씀드리세요

**Comment by jkang1201** [comment]
아 죄송합니다 두 분을 헷갈렸네요 pathvariable로 구현해서 노션에 올릴게요
