### ISSUE TITLE
프로젝트 알림 조회 & 컨펌시 알림 확인 값 반영여부 질문드려요 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#298]
프로젝트 알림 조회 및 컨펌에 대한 기획은 원래 아래처럼 되는데요,  

- 프로젝트 알림 조회 - 알림 확인 여부(db테이블 상에서 check_yn 칼럼 해당)가 false인 것만 조회
- 프로젝트 알림 컨펌 - 알림 타입에 따라 다음 같이 프로세스를 진행:  
   - 업무 알림 컨펌 : 신뢰도 부여/차감 + 신뢰도 이력 남기기 + 알림 확인 여부 true로 업데이트
   - 모집 알림 컨펌 : 프로젝트 참가 수락/거절 + 알림 확인 여부 true로 업데이트
   - 크루 알림 컨펌 : 알림 확인 여부 true로 업데이트 

알림 확인 여부 true로 업데이트 하는 프로세스도 소스상에 같이 구현 되어 있을까요?

**Comment by jkang1201** [comment]
제가 작성한 코드가 아니라서 잘 모르겠네요...

**Comment by EUNSUN23** [comment]
> 제가 작성한 코드가 아니라서 잘 모르겠네요...

그럼 작성하신 신뢰도 점수 부여/차감 하는 프로세스에는 알림 테이블 update 하는 건 따로 포함 안되어있는건가요?

**Comment by jkang1201** [comment]
제 코드에는 없습니다
