### ISSUE TITLE
프로젝트 알림 확인여부 update api 추가 요청 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#300]
**프로젝트 알림 조회 & 컨펌 프로세스 기획**
- 프로젝트 알림 조회 - 알림 확인 여부(db테이블 상에서 check_yn 칼럼 해당)가 false인 것만 조회
- 프로젝트 알림 컨펌 - 알림 타입에 따라 다음 같이 프로세스를 진행:  
   - 업무 알림 컨펌 : 신뢰도 부여/차감 + 신뢰도 이력 남기기 + 알림 확인 여부 true로 업데이트
   - 모집 알림 컨펌 : 프로젝트 참가 수락/거절 + 알림 확인 여부 true로 업데이트
   - 크루 알림 컨펌 : 알림 확인 여부 true로 업데이트 
--------------------------

위 기획에서 '알림 확인 여부 true로 업데이트' 이 기능에 대한  프로세스 및 api 생성 요청드립니다. 

**<예상 요청 파라미터>** 
```
{
alertId: 알림Id 
check_yn : 알림확인여부(true/false)
}
```

**<예상 프로세스>**
alertId로 알림테이블(alert) 조회해서 check_yn 요청 파라미터값으로 업데이트 

**<예상 응답값 >**
```
{
result: 'success',
message: 'success'
} 
```

**Comment by jkang1201** [comment]
PR 만들었고, Notion에 추가했습니다
