### ISSUE TITLE
프로젝트 업무 조회 api 응답값 중 할당자 수정 요청

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#301]
**api: /api/work/project/{projectId}/milestone/{mileStoneId}, /api/work/{workId}**

위 api 응답값중 assignedUserNickName 이 값 대신 

```
assignedUser: {
projectMemberId: long,
nickname: string
}
```
위 객체로 보내주실 수 있을까요? 코드상에 수정할게 많으시면 기존대로 응답값 주시고, 프론트단에서 필요한 처리 하는걸로 할게요.

**Comment by songhyeonpk** [comment]
닉네임 정보만 필요하시다고 하셨었는데 ID 값도 필요한건가요? 
그리고 업무 생성 로직을 보니까 할당 회원 정보를 User 엔티티의 ID 값을 요청받던데 Project Member 엔티티의 ID 값을 요청받아야 하나요?

**Comment by EUNSUN23** [comment]
> 닉네임 정보만 필요하시다고 하셨었는데 ID 값도 필요한건가요? 그리고 업무 생성 로직을 보니까 할당 회원 정보를 User 엔티티의 ID 값을 요청받던데 Project Member 엔티티의 ID 값을 요청받아야 하나요?

1) 생성쪽은 그렇게 되어있을 줄 몰랐네요... 저는 api 명세만 보고 작업하는 거라.. 근데 Project Member 엔티티 id가 맞을듯해요.. 

2) id값이 필요한 이유는 프로젝트 전체 멤버 데이터 (/api/projectmember/project/{projectId} 통해서 조회하는 데이터) 와 form을 맞추기 위해서에요. form이 맞지 않아도, 프론트단에서 처리할 수 있는 방법은 있지만 코드가 좀 복잡해지는 경향이 있어요.  만약에 작업하고 계신게 많아서 부담스러우시면, 프론트단에서 처리하는걸로 하구요.

**Comment by songhyeonpk** [comment]
서버단에서 저렇게 수정해서 응답해드리겠습니다.

**Comment by EUNSUN23** [comment]
> 서버단에서 저렇게 수정해서 응답해드리겠습니다.

네 감사합니다~

**Comment by songhyeonpk** [comment]
지금 Work 엔티티에 AssignedUser는 User 엔티티 형태로 저장이 되고 있는데요. 응답 값 중 id를 User ID(PK)를 드려야 할까요 아님 ProjectMember 엔티티를 조회해서 ProjectMember ID(PK)를 드려야 할까요?

**Comment by EUNSUN23** [comment]
ProjectMember의 ID값 주시면 될 것 같아요

**Comment by songhyeonpk** [comment]
```
    "data": {
        "content": [
            {
                "workId": 28,
                "projectId": 12,
                "milestoneId": 21,
                "assignedUser": {
                    "projectMemberId": 19,
                    "nickname": "mmm123"
                },
                "lastModifiedMemberNickname": "mmm123",
                "content": "프로젝트12 > 마일스톤21 > 업무 내용7",
                "startDate": "2024-01-18",
                "endDate": "2024-01-20",
                "progressStatus": "완료"
            },
            {
                "workId": 74,
                "projectId": 12,
                "milestoneId": 21,
                "assignedUser": {
                    "projectMemberId": 19,
                    "nickname": "mmm123"
                },
                "lastModifiedMemberNickname": "mmm123",
                "content": "프로젝트12 > 마일스톤21 > 업무 내용8",
                "startDate": "2024-02-01",
                "endDate": "2024-02-10",
                "progressStatus": "진행중"
            },
            {
                "workId": 81,
                "projectId": 12,
                "milestoneId": 21,
                "assignedUser": {
                    "projectMemberId": 73,
                    "nickname": "zzz123"
                },
                "lastModifiedMemberNickname": "zzz123",
                "content": "프로젝트12 > 마일스톤21 > 업무 내용9",
                "startDate": "2024-02-01",
                "endDate": "2024-02-10",
                "progressStatus": "시작전"
            }
        ],
        "totalPages": 9
    }
```

**Comment by EUNSUN23** [comment]
> ```
>     "data": {
>         "content": [
>             {
>                 "workId": 28,
>                 "projectId": 12,
>                 "milestoneId": 21,
>                 "assignedUser": {
>                     "projectMemberId": 19,
>                     "nickname": "mmm123"
>                 },
>                 "lastModifiedMemberNickname": "mmm123",
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용7",
>                 "startDate": "2024-01-18",
>                 "endDate": "2024-01-20",
>                 "progressStatus": "완료"
>             },
>             {
>                 "workId": 74,
>                 "projectId": 12,
>                 "milestoneId": 21,
>                 "assignedUser": {
>                     "projectMemberId": 19,
>                     "nickname": "mmm123"
>                 },
>                 "lastModifiedMemberNickname": "mmm123",
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용8",
>                 "startDate": "2024-02-01",
>                 "endDate": "2024-02-10",
>                 "progressStatus": "진행중"
>             },
>             {
>                 "workId": 81,
>                 "projectId": 12,
>                 "milestoneId": 21,
>                 "assignedUser": {
>                     "projectMemberId": 73,
>                     "nickname": "zzz123"
>                 },
>                 "lastModifiedMemberNickname": "zzz123",
>                 "content": "프로젝트12 > 마일스톤21 > 업무 내용9",
>                 "startDate": "2024-02-01",
>                 "endDate": "2024-02-10",
>                 "progressStatus": "시작전"
>             }
>         ],
>         "totalPages": 9
>     }
> ```

넵 감사합니다~
