### ISSUE TITLE
게시글 전체 조회 totalElements 오류

### ISSUE THREAD

**Issue by moa1128** [oneMonthProject/Backend#313]
현재 코드를 보니까 전체 아이템 개수를 가져오는 부분이 잘못된 것 같습니다.
offset 과 limit 으로 자른 List 의 size 로 총 개수로 설정하면 pageable 의 size 이상의 수가 들어와도 size 값만 나올 것 같습니다.

요청사항은 아래와 같습니다.
- total 값 설정 로직 수정
- 현재 5 로 설정되어 있는 pageable size 를 8 로 수정
- 최신순으로 정렬

**Comment by songhyeonpk** [comment]
확인했습니다
