### ISSUE TITLE
프로젝트 알림 컨펌 프로세스 구현 요청 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#332]
<프로젝트 알림 컨펌 프로세스> 
- **아래 굵게 표시한 프로세스 api 구현이 필요합니다.** 

1. 업무 알림 컨펌 : 
   - **신뢰도 부여/차감 + 신뢰도 이력 남기기** (현재 api 명세서에 신뢰도 부여/차감 api가 따로 만들어져 있는데, api가 따로 있는게 아니라 '업무 알림 컨펌' 이라는 api 요청을 보내면 백엔드에서 신뢰도 부여/차감 + 신뢰도 이력 남기기 프로세스를 같이 처리해야 합니다) 
    
   - 알림 확인 여부 true로 업데이트 (프론트측에서 api 요청 보냄. api 구현 완료)
  
2. 모집 알림 컨펌 : 
   - **프로젝트 참가 수락/거절** (#350)
  
   - 알림 확인 여부 true로 업데이트 (프론트측에서 api 요청 보냄. api 구현 완료)

3. 크루 알림 컨펌 :
   - 알림 확인 여부 true로 업데이트 (프론트측에서 api 요청 보냄. api 구현 완료)

**Comment by songhyeonpk** [comment]
확인했습니다

**Comment by songhyeonpk** [comment]
**1. 업무 알림 컨펌 - 신뢰도 부여/차감 + 신뢰도 이력 남기기**

- 예상 요청 값
```
{
    "alertId": Long,
    "scoreTypeId": Long(1 or 2)   # '+': 1, '-': 2
}
```
