### ISSUE TITLE
사용자 프로필 이미지 조회 방법 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#339]
백엔드에서 응답한 profileImgSrc 로 프론트에서 이미지 조회하는 api는 별도 생성 필요 없을까요?

**Comment by songhyeonpk** [comment]
응답한 profileImgSrc를 이미지 태그의 src 속성에 셋팅하면 되지 않나요?

**Comment by EUNSUN23** [comment]
> 응답한 profileImgSrc를 이미지 태그의 src 속성에 셋팅하면 되지 않나요?

아 네 확인했습니다~!
