### ISSUE TITLE
프로젝트 마일스톤별 업무 조회 api 응답값 에러 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#349]
api : api/work/project/{projectId}/milestone/{milestoneId}?pageIndex={pageIndex}&itemCount={itemCount}

api/work/project/69/milestone/94?pageIndex=0&itemCount=8 으로 요청 보냈을때 응답값이 
빈 객체형태로 옵니다. 확인 부탁드려요 

### 요청헤더

![image](https://github.com/oneMonthProject/Backend/assets/60612115/c229ca4c-b108-4a4a-9195-118b0e1c556e)

### 응답값

![image](https://github.com/oneMonthProject/Backend/assets/60612115/c99764ea-dfa3-40d5-b05a-f1c19113e0e8)

**Comment by songhyeonpk** [comment]
지금 해당 db를 확인했을 때, 업무 테이블에 데이터가 존재하지 않습니다

**Comment by EUNSUN23** [comment]
데이터가 존재하지 않아도 {result:success, message:success, data:{}} 이런식으로 프론트에서 메세지라던가 보여줄수있는 데이터가 와야하지 않을까요? ㅎ..

**Comment by songhyeonpk** [comment]
확인했는데 {result:success, message:success, data:{}} 형식으로 응답되도록 설정되어있습니다 상태코드는 200으로 응답되나요?

**Comment by EUNSUN23** [comment]
위에 에러는 프론트 코드가 문제였는데, 고친 후에 

/api/work/project/69/milestone/94?pageIndex=0&itemCount=8 이렇게 보내는데 

{"result":"fail","message":"한 페이지에 요청할 수 있는 데이터의 개수 범위를 확인해주세요.","data":null}

이렇게 응답이 오고 있어요 확인 부탁드려요

**Comment by songhyeonpk** [comment]
> 위에 에러는 프론트 코드가 문제였는데, 고친 후에
> 
> /api/work/project/69/milestone/94?pageIndex=0&itemCount=8 이렇게 보내는데
> 
> {"result":"fail","message":"한 페이지에 요청할 수 있는 데이터의 개수 범위를 확인해주세요.","data":null}
> 
> 이렇게 응답이 오고 있어요 확인 부탁드려요

api 로직에서 itemCount를 최대 6개로 제한하고 있어요. 혹시 수정해야할까요?

**Comment by EUNSUN23** [comment]
> > 위에 에러는 프론트 코드가 문제였는데, 고친 후에
> > /api/work/project/69/milestone/94?pageIndex=0&itemCount=8 이렇게 보내는데
> > {"result":"fail","message":"한 페이지에 요청할 수 있는 데이터의 개수 범위를 확인해주세요.","data":null}
> > 이렇게 응답이 오고 있어요 확인 부탁드려요
> 
> api 로직에서 itemCount를 최대 6개로 제한하고 있어요. 혹시 수정해야할까요?

음 아뇨 6개가 맞을것같네요

**Comment by songhyeonpk** [comment]
> 음 아뇨 6개가 맞을것같네요

넵 그럼 이슈 close 하겠습니다.
