### ISSUE TITLE
모집 알림 컨펌 프로세스중 거절/수락 프로세스 구현 (Related to: #332)

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#350]
## 모집 알림 컨펌 프로세스중 거절/수락 프로세스 구현 (Related to: #332)

<br>

- [x] **프로젝트 알림 테이블에 모집 거절/수락 칼럼 추가 (데이터 타입은 boolean, 최초 생성시에는 null값임)**

<br>

- [x] **지원 수락/거절 프로세스 & api 생성**
   -  지원 수락 :  수락/거절 데이터 true로 업데이트하고 프로젝트 크루 참여 알림 **(프로젝트 전 멤버 확인 가능)**  새로 생성 (check_user값은 따로 설정 x) 
   -  지원 거절 :  수락/거절 데이터 false로 업데이트 

<br>

- [ ] **사용자가 지원한 프로젝트에 대한 수락/거절 여부 조회 프로세스 & api**

   - 예상 요청 파라미터 
      ```
      {
	      userId: xxx 
      }
      ```
   - 예상 응답 데이터 
      ```
      {
	      result:'success',
	      message:'success',
	      data: {
		      project:{
			      projectId:xxx,
			      projectName:xxx
		      },
		      position : {
			      positionId: xxx,
			      positionName: xxx
		      },
		      status_recruit : true / false 
	      }
	      
      }
      ```

**Comment by songhyeonpk** [comment]
요청 파라미터로 userId를 받지 않고 로그인한 회원의 id를 사용해도 될까요?

**Comment by songhyeonpk** [comment]
3번 api의 요청 파라미터에 지원한 알림의 ID(PK) 값이 필요할 것 같습니다.

**Comment by EUNSUN23** [comment]
> 3번 api에서 요청 파라미터를 따로 받지 않고 로그인한 회원의 id를 사용해도 될까요?

아 넵 괜찮아요~ 파라미터 없이 보내겠습니다

**Comment by EUNSUN23** [comment]
> 3번 api에서 지원한 알림의 ID(PK) 값을 요청받을 수 있을까요?

지원한 알림 pk는 저 api 보낼 당시에는 모를것같아요. 저 api 요청을 언제, 왜 보내냐면요, 

![image](https://github.com/oneMonthProject/Backend/assets/60612115/0001dc70-1a15-4853-aa6a-dae99368c593)


저 빨간 영역에 알림아이콘 추가하고, 클릭하면 사용자 알림 목록 조회하게 할거라서요, 요청 파라미터로 사용자 아이디값 보내면 그걸로 알림 테이블의 send_user_id 일치하는것, 그리고 수락/거절 status가 null이 아닌 목록 조회하면 될것 같아요

**Comment by songhyeonpk** [comment]
확인했습니다. 전체 목록을 조회하는거였네요 그럼 페이징도 적용해야될까요?

**Comment by EUNSUN23** [comment]
> 확인했습니다. 전체 목록을 조회하는거였네요 그럼 페이징도 적용해야될까요?

음 넵 페이징처리해주시면 좋을 것 같아요. itemCount, pageIndex 같이 보내겠습니다.

**Comment by songhyeonpk** [comment]
> 음 넵 페이징처리해주시면 좋을 것 같아요. itemCount, pageIndex 같이 보내겠습니다.

넵 최신순 정렬적용해서 보내겠습니다.

**Comment by EUNSUN23** [comment]
> > 음 넵 페이징처리해주시면 좋을 것 같아요. itemCount, pageIndex 같이 보내겠습니다.
> 
> 넵 최신순 정렬적용해서 보내겠습니다.

넵넵
