### ISSUE TITLE
프로젝트 마일스톤 진행상태 '진행중' 으로만 수정 되는 버그 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#354]
api: /api/milestone, PATCH 

다음같이 요청 보냈을 때 

![image](https://github.com/oneMonthProject/Backend/assets/60612115/b510ea7e-c23d-4ce0-bb93-84ace7e6f660)

응답은 정상으로 오는데요, 
![image](https://github.com/oneMonthProject/Backend/assets/60612115/a880fbde-e496-4ea7-aba5-ae42504b9962)

마일스톤 진행상태는 어떤 값으로 바꿔도 계속 '진행중' 이 되는것같아요. 확인부탁드립니다

**Comment by songhyeonpk** [comment]
milestoneId는 PathVariable로 요청받고 있습니다. /api/milestone/{milestoneId} 경로로 요청해도 변경이 안되나요?
