### ISSUE TITLE
프로젝트 멤버 목록 조회 api 버그 확인 요청

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#361]
api : /api/projectmember/project/{projectId} 

projectId값에 69 넣어서 요청보냈을때 응답이 아래같이 오는데요,  확인 부탁드립니다. (프로젝트 멤버가 한명 있어야 합니다. 이 프로젝트 생성한 사람이요)  

<img width="589" alt="image" src="https://github.com/oneMonthProject/Backend/assets/60612115/048d9a8f-13ea-41c2-94e0-f3741aed88ea">

**Comment by songhyeonpk** [comment]
넵 확인해보겠습니다
