### ISSUE TITLE
기능 확인요청 : 사용자 신뢰점수 가감시 가감결과에 따른 신뢰등급 업데이트

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#362]
사용자 신뢰점수 가감될때 신뢰등급도 업데이트 되고 있을까요? 확인 부탁드려요

**Comment by songhyeonpk** [comment]
4등급 max 값을 200, 3등급 min 값을 201로 임시변경하고 현재 신뢰점수가 200점인 회원이 업무를 완료해서 +30점을 받았을 때 4등급 -> 3등급으로 변경되는거 확인했습니다.

**Comment by EUNSUN23** [comment]
넵 감사합니다~

**Comment by songhyeonpk** [comment]
> 넵 감사합니다~

-했을 때 3등급 -> 4등급으로 변경되는것도 확인했습니다. 이슈 닫겠습니다
