### ISSUE TITLE
프로젝트 멤버 상세조회 api 응답값 버그 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#365]
api : /api/projectmember/{projectMemberId}, POST

/api/projectmember/77 이렇게 요청 보냈을때 응답값 중 user.nickname이 닉네임이 아니라 이메일로 오고 있는데요, 확인 부탁드립니다.

**Comment by songhyeonpk** [comment]
확인했는데 nickname에 email 값을 셋팅하고 있네요. 바로 수정하겠습니다.
