### ISSUE TITLE
프로젝트 알림 생성 api 요청 body 문의 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#366]
**API 엔드포인트 :**` /api/alert, POST `

**문의 :** 

기존 요청 body 데이터에 checkUserId, sendUserId도 workId나 positionId처럼 nullable로 해주실 수 있나요? 둘 다 경우에 따라 파라미터로 넣지 않아도 되거나 넣기 애매할 때가 있어서요.

**Comment by songhyeonpk** [comment]
checkUser는 nullable로 변경하긴 했는데요. sendUser도 nullable로 변경이 필요할까요?
