### ISSUE TITLE
프로젝트 알림 상태 업데이트 api 응답 에러 외

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#389]
### 1. 프로젝트 알림 상태 업데이트 api 응답에러 

**API endpoint :** ` /api/alert/{alertId}/status `

**문의 :** 응답값이 500으로 오는데, 위 alertId를 165로 해서 응답에러 확인 부탁드립니다. 

### 2. PR merge 확인 & 스프링부트 서버 재기동 요청 

로그인한 유저 외에 일반 사용자 정보 조회하는 api가 필요해서 직접 작업해서 pr 올리고 merge했는데 깃헙액션은 동작 안 하는것 같아요. 
백엔드 배포 서버에 수정한 소스 반영되게 해 주시고 스프링부트 서버 재기동 부탁드려요.

**Comment by songhyeonpk** [comment]
알림 확인상태 변경 api 요청에서 발생하는 오류 해결했고 해당 api는 하나의 값만 수정 하는 요청이여서 PutMapping -> PatchMapping으로 변경했습니다.
배포까지 완료했습니다. 한번 확인부탁드려요!
