### ISSUE TITLE
프로젝트 모집 알림 컨펌 API 요청시 404 에러 응답 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#393]
**API endpoint:**  `/api/project/{projectId}/participate/confirm` , `POST`

**요청 url파라미터:** `69`

**요청 body:**  `{ alertId: 203, confirmResult: true }`

위 요청 보냈을 때 404 응답이 오고 있어요. 확인 부탁드립니다. 

![image](https://github.com/oneMonthProject/Backend/assets/60612115/407c4ce8-d25e-4c9c-b55a-1763197ac170)

**Comment by songhyeonpk** [comment]
프로젝트 모집 알림 컨펌 API의 엔드포인드는 `POST` `/api/project/participate/confirm` 으로 되어있습니다. 해당 요청에서는 해당 알림의 ID(PK) 값을 요청받고 있어서 따로 {projectId}는 받고 있지 않습니다

**Comment by EUNSUN23** [comment]
넵 수정하고 응답 잘 받네요
