### ISSUE TITLE
프로젝트 설정 페이지에 필요한 api 구현 요청 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#396]
## 프로젝트 설정 페이지 

<br/>

![image](https://github.com/oneMonthProject/Backend/assets/60612115/179a75a5-220a-4fd9-868a-0c4912014eaf)

<br/>

### 1. 프로젝트 정보 수정 api 

```
// 예상 요청 body:
{
	projectId: long,
	projectName: string, // 프로젝트 이름
	subject: string, // 프로젝트 주제 
	trustGradeCode: int, // 1, 2, 3, 4 등 
	startDate: string, // yyyy-mm-dd
	endDate: string // yyyy-mm-dd
}

```
### 2. 프로젝트 종료 api 

- 논의 필요 
   - 백엔드에서 관리하는 프로젝트 상태값 어떻게 관리하고 있는지? (상수값? db데이터?)

**Comment by songhyeonpk** [comment]
프로젝트 수정 api에서 응답 값은 따로 필요하지 않나요?

**Comment by EUNSUN23** [comment]
> 프로젝트 수정 api에서 응답 값은 따로 필요하지 않나요?

네 클라이언트에서 데이터 리프레쉬하면 되서 수정된 프로필 정보는 안 보내주셔도 되고, 다른 응답들처럼 resuilt message만 보내주시면 되요
