### ISSUE TITLE
업무 생성시 담당자 ID 매핑 에러 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#403]
**API endpoint:** `/api/work/project/{projectid}/milestone/{milestoneId} `

**내용 :**  업무 생성시 assignedUserId에 담아서 보내는 id로 담당자 매핑이 안되는 것 같아요. 업무 업데이트 시에도 동일한 에러 발생합니다. 

**요청 body:** 
```
{
	content: "업무6",
	startDate: "2024-02-09",
	endDate: "2024-02-13",
	assignedUserId: "279"
}
```

**업무 조회 응답 body :** 

<img width="1068" alt="image" src="https://github.com/oneMonthProject/Backend/assets/60612115/62c6d813-4bdd-48ca-9b41-deb5b8eccd8b">

**Comment by songhyeonpk** [comment]
저번에 업무 생성 시 assignedUserId 필드에 project_member_id 값을 요청하기로 얘기됐었는데요. project_member_id로 요청해도 오류가 발생하나요?

**Comment by EUNSUN23** [comment]
네 project_member_id 로 보내고 있어요

**Comment by songhyeonpk** [comment]
확인해보겠습니다. #396 1번 관련해서 PR 작성했는데 한번 확인부탁드려요
