### ISSUE TITLE
참여하고 있는 프로젝트 목록 조회 api 응답 에러 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#409]
참여중인 프로젝트 목록 조회 api 요청시 응답값이 아래처럼 오고있는데 확인 부탁드려요. 요청 파라미터중 itemCount값은 8입니다.  

```
{
    "result": "fail",
    "message": "한 페이지에 요청할 수 있는 데이터의 개수 범위를 확인해주세요.",
    "data": null
}
```

**Comment by songhyeonpk** [comment]
itemCount 6개 이상 요청 시 예외처리하고 있습니다. 수정할까요?

**Comment by EUNSUN23** [comment]
> itemCount 6개 이상 요청 시 예외처리하고 있습니다. 수정할까요?

넵 원래 8개였던것같아요
