### ISSUE TITLE
종료된 프로젝트가 게시글 totalPages에 포함되는 에러 

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#415]
**API endpoint:** `/api/board/search/public`

**내용 :**  게시글 조회시 종료된 프로젝트 관련 게시글은 조회를 하지 않는데 응답데이터 중 totalPages에는 포함이 되는 것 같습니다.  

### 게시글 화면 

<img width="1347" alt="image" src="https://github.com/oneMonthProject/Backend/assets/60612115/b6c29746-0be7-428f-834c-81979ae7d0d0">

### 응답 데이터값 

```
{
    "result": "success",
    "message": "success",
    "data": {
        "content": [
            // 생략 
        ],
        "totalPages": 14 
    }
}
```

**Comment by songhyeonpk** [comment]
해당 요청에서 게시글의 모집상태가 모집중인 게시글 목록만을 조회하면 되는건가요?

**Comment by EUNSUN23** [comment]
> 해당 요청에서 게시글의 모집상태가 모집중인 게시글 목록만을 조회하면 되는건가요?

넵 맞아요
