### ISSUE TITLE
완료/만료된 알림 삭제 요청시 에러 발생

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#422]
현재 완료/만료된 업무 삭제 요청을 보내면 아래 응답이 오고 있는데요, 

```
{
    "timestamp": "2024-02-15T10:32:38.016+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/work/378"
}
```

제 생각에는 완료/만료된 업무는 알림테이블과 관계가 생긴 상태이기때문에 삭제하려고 하면 에러가 발생하는 것 같아요. 

(업무 상태 상관없이)업무 삭제시 연관된 알림도 같이 삭제되도록 수정 가능하실까요?

**Comment by songhyeonpk** [comment]
넵 알겠습니다

**Comment by songhyeonpk** [comment]
수정 후 배포했습니다.

**Comment by EUNSUN23** [comment]
> 수정 후 배포했습니다.

넵 확인해보겠습니다
