### ISSUE TITLE
회원 프로필 조회 api 명세 수정 요청

### ISSUE THREAD

**Issue by EUNSUN23** [oneMonthProject/Backend#58]
**수정 내용** : /api/user/me -> /api/user/{id}

**요청 이유** : 회원 상세정보 조회 api가 사용자 개인 프로필 페이지 뿐 아니라 프로젝트 멤버 상세 정보 조회시에도 필요한데요, 
회원 아이디에 따라 회원 프로필 정보 조회가 가능했으면 합니다.

**Comment by songhyeonpk** [comment]
넵 수정하도록 하겠습니다.
